import FWCore.ParameterSet.Config as cms

from Validation.MtdValidation.btlSimHitsPostProcessor_cfi import btlSimHitsPostProcessor
from Validation.MtdValidation.btlLocalRecoPostProcessor_cfi import btlLocalRecoPostProcessor
from Validation.MtdValidation.MtdTracksPostProcessor_cfi import MtdTracksPostProcessor

mtdValidationPostProcessor = cms.Sequence(btlSimHitsPostProcessor + btlLocalRecoPostProcessor + MtdTracksPostProcessor)
